import type { Product } from '@ankita/types'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Banarasi Silk Saree in Midnight Blue',
    slug: 'banarasi-silk-saree-midnight-blue',
    sku: 'AP-SAR-001',
    description: 'A stunning handwoven Banarasi silk saree in deep midnight blue with intricate gold zari work. Perfect for weddings and festive occasions.',
    shortDescription: 'Handwoven Banarasi silk with gold zari',
    categoryId: 'cat-1',
    category: { id: 'cat-1', name: 'Sarees', slug: 'sarees', sortOrder: 1, isActive: true, productCount: 50, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
    brand: 'Ankita',
    fabric: 'Silk',
    gender: 'FEMALE',
    images: [{ id: 'img-1', productId: '1', url: '', altText: 'Banarasi Silk Saree', sortOrder: 0, isPrimary: true, createdAt: '2026-01-01', updatedAt: '2026-01-01' }],
    variants: [
      { id: 'var-1', productId: '1', sku: 'AP-SAR-001-FS', color: 'Midnight Blue', colorHex: '#191970', size: 'Free Size', mrp: 8999, sellingPrice: 6999, stock: 15, lowStockThreshold: 3, isActive: true, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
    ],
    mrp: 8999,
    sellingPrice: 6999,
    gstRate: 5,
    hsnCode: '5007',
    isReturnable: false,
    isExchangeable: false,
    returnWindow: 0,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isPublished: true,
    avgRating: 4.8,
    totalReviews: 234,
    totalSold: 1200,
    createdAt: '2026-08-01',
    updatedAt: '2026-09-01',
  },
  {
    id: '2',
    name: 'Embroidered Anarkali Kurti Set',
    slug: 'embroidered-anarkali-kurti-set',
    sku: 'AP-KUR-001',
    description: 'An elegant Anarkali kurti with intricate thread embroidery in soft rose pink. Comes with matching palazzo and dupatta for a complete ethnic look.',
    shortDescription: 'Thread embroidered Anarkali with palazzo & dupatta',
    categoryId: 'cat-2',
    category: { id: 'cat-2', name: 'Kurtis', slug: 'kurtis', sortOrder: 2, isActive: true, productCount: 80, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
    brand: 'Ankita',
    fabric: 'Georgette',
    gender: 'FEMALE',
    images: [{ id: 'img-2', productId: '2', url: '', altText: 'Anarkali Kurti Set', sortOrder: 0, isPrimary: true, createdAt: '2026-01-01', updatedAt: '2026-01-01' }],
    variants: [
      { id: 'var-2', productId: '2', sku: 'AP-KUR-001-S', color: 'Rose Pink', colorHex: '#FF69B4', size: 'S', mrp: 3499, sellingPrice: 2499, stock: 20, lowStockThreshold: 5, isActive: true, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
      { id: 'var-3', productId: '2', sku: 'AP-KUR-001-M', color: 'Rose Pink', colorHex: '#FF69B4', size: 'M', mrp: 3499, sellingPrice: 2499, stock: 18, lowStockThreshold: 5, isActive: true, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
      { id: 'var-4', productId: '2', sku: 'AP-KUR-001-L', color: 'Rose Pink', colorHex: '#FF69B4', size: 'L', mrp: 3499, sellingPrice: 2499, stock: 12, lowStockThreshold: 5, isActive: true, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
    ],
    mrp: 3499,
    sellingPrice: 2499,
    gstRate: 12,
    hsnCode: '6211',
    isReturnable: true,
    isExchangeable: true,
    returnWindow: 7,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isPublished: true,
    avgRating: 4.6,
    totalReviews: 189,
    totalSold: 890,
    createdAt: '2026-08-15',
    updatedAt: '2026-09-10',
  },
  {
    id: '3',
    name: 'Floral Wrap Midi Dress',
    slug: 'floral-wrap-midi-dress',
    sku: 'AP-DRS-001',
    description: 'A versatile wrap-style midi dress featuring a beautiful floral print on premium rayon fabric. Effortlessly chic for brunches, outings, and casual evenings.',
    shortDescription: 'Floral print rayon wrap midi dress',
    categoryId: 'cat-3',
    category: { id: 'cat-3', name: 'Dresses', slug: 'dresses', sortOrder: 3, isActive: true, productCount: 60, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
    brand: 'Ankita',
    fabric: 'Rayon',
    gender: 'FEMALE',
    images: [{ id: 'img-3', productId: '3', url: '', altText: 'Floral Wrap Dress', sortOrder: 0, isPrimary: true, createdAt: '2026-01-01', updatedAt: '2026-01-01' }],
    variants: [
      { id: 'var-5', productId: '3', sku: 'AP-DRS-001-S', color: 'Coral Floral', colorHex: '#FF6B6B', size: 'S', mrp: 2299, sellingPrice: 1599, stock: 25, lowStockThreshold: 5, isActive: true, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
      { id: 'var-6', productId: '3', sku: 'AP-DRS-001-M', color: 'Coral Floral', colorHex: '#FF6B6B', size: 'M', mrp: 2299, sellingPrice: 1599, stock: 30, lowStockThreshold: 5, isActive: true, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
    ],
    mrp: 2299,
    sellingPrice: 1599,
    gstRate: 12,
    hsnCode: '6204',
    isReturnable: true,
    isExchangeable: true,
    returnWindow: 7,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    isPublished: true,
    avgRating: 4.4,
    totalReviews: 145,
    totalSold: 670,
    createdAt: '2026-09-01',
    updatedAt: '2026-09-15',
  },
  {
    id: '4',
    name: 'Pastel Co-ord Set — Lavender',
    slug: 'pastel-co-ord-set-lavender',
    sku: 'AP-CRD-001',
    description: 'A dreamy lavender co-ord set featuring a cropped blazer and straight-leg trousers. Perfect for office, brunch, or a day out.',
    shortDescription: 'Lavender blazer & trouser co-ord set',
    categoryId: 'cat-4',
    category: { id: 'cat-4', name: 'Co-ord Sets', slug: 'co-ord-sets', sortOrder: 4, isActive: true, productCount: 40, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
    brand: 'Ankita',
    fabric: 'Crepe',
    gender: 'FEMALE',
    images: [{ id: 'img-4', productId: '4', url: '', altText: 'Lavender Co-ord Set', sortOrder: 0, isPrimary: true, createdAt: '2026-01-01', updatedAt: '2026-01-01' }],
    variants: [
      { id: 'var-7', productId: '4', sku: 'AP-CRD-001-XS', color: 'Lavender', colorHex: '#E6E6FA', size: 'XS', mrp: 3799, sellingPrice: 2899, stock: 10, lowStockThreshold: 3, isActive: true, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
      { id: 'var-8', productId: '4', sku: 'AP-CRD-001-S', color: 'Lavender', colorHex: '#E6E6FA', size: 'S', mrp: 3799, sellingPrice: 2899, stock: 15, lowStockThreshold: 3, isActive: true, createdAt: '2026-01-01', updatedAt: '2026-01-01' },
    ],
    mrp: 3799,
    sellingPrice: 2899,
    gstRate: 12,
    hsnCode: '6211',
    isReturnable: true,
    isExchangeable: true,
    returnWindow: 7,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isPublished: true,
    avgRating: 4.7,
    totalReviews: 210,
    totalSold: 980,
    createdAt: '2026-07-15',
    updatedAt: '2026-09-05',
  },
]
